package project.backend.services;

import java.util.List;
import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import project.backend.domain.AiTransformType;
import project.backend.domain.Photo;
import project.backend.domain.PhotoStatus;
import project.backend.domain.User;
import project.backend.dto.EditOperationResponse;
import project.backend.dto.EditSuggestion;
import project.backend.dto.EditSuggestionResponse;
import project.backend.dto.PhotoResponse;
import project.backend.exception.BadRequestException;
import project.backend.exception.GeminiException;
import project.backend.exception.ImageKitUploadException;
import project.backend.exception.ResourceNotFoundException;
import project.backend.repository.PhotoRepository;
import project.backend.services.ImageEditMapper.EditOperation;

/**
 * "Describe an edit" in the AI edit dialog: Gemini looks at the photo and the
 * instruction and suggests how to do it; the edit itself is always an ImageKit
 * URL transformation, so previews are instant and nothing is generated by AI.
 * Without Gemini the instruction is keyword-matched to the same operations.
 */
@Service
public class ImageEditService {

    private static final Logger log = LoggerFactory.getLogger(ImageEditService.class);

    private final PhotoRepository photoRepository;
    private final ImageKitService imageKitService;
    private final GeminiService geminiService;
    private final PhotoService photoService;

    public ImageEditService(
            PhotoRepository photoRepository,
            ImageKitService imageKitService,
            GeminiService geminiService,
            PhotoService photoService
    ) {
        this.photoRepository = photoRepository;
        this.imageKitService = imageKitService;
        this.geminiService = geminiService;
        this.photoService = photoService;
    }

    public EditSuggestionResponse suggest(User user, UUID photoId, String instruction) {
        Photo photo = getActivePhoto(user, photoId);
        String trimmed = instruction.trim();

        String suggestion = null;
        String aiMessage = null;
        List<String> aiOperations = List.of();

        if (!geminiService.isConfigured()) {
            aiMessage = "AI suggestions aren't configured, so your request was matched to ImageKit edits directly.";
        } else {
            try {
                byte[] image = imageKitService.downloadForAnalysis(photo.getUrl());
                EditSuggestion result = geminiService.editSuggestion(image, "image/jpeg", trimmed);
                suggestion = result.suggestion();
                aiOperations = result.operations();
            } catch (GeminiException | ImageKitUploadException ex) {
                log.info("Edit suggestion fell back to keyword matching: {}", ex.getMessage());
                aiMessage = ex.getMessage() + " Your request was matched to ImageKit edits directly.";
            }
        }

        List<EditOperation> operations = ImageEditMapper.resolve(trimmed, aiOperations);
        String chain = ImageEditMapper.buildChain(operations, photo.getWidth(), photo.getHeight());
        String previewUrl = operations.isEmpty() ? null : imageKitService.buildAiTransformUrl(photo.getUrl(), chain);

        return new EditSuggestionResponse(
                trimmed,
                suggestion,
                suggestion != null,
                aiMessage,
                operations.stream().map(op -> new EditOperationResponse(op.key(), op.label(), op.note())).toList(),
                operations.isEmpty() ? null : chain,
                previewUrl);
    }

    /** Renders the transformation through ImageKit and stores the result as a new photo. */
    public PhotoResponse saveAsNewPhoto(User user, UUID photoId, List<String> operationKeys) {
        Photo photo = getActivePhoto(user, photoId);
        List<EditOperation> operations = ImageEditMapper.fromKeys(operationKeys);
        if (operations.isEmpty()) {
            throw new BadRequestException("None of the requested edits are supported");
        }

        String chain = ImageEditMapper.buildChain(operations, photo.getWidth(), photo.getHeight());
        String transformUrl = imageKitService.buildAiTransformUrl(photo.getUrl(), chain);
        byte[] bytes = imageKitService.downloadTransformedImage(transformUrl);

        boolean transparent = operations.contains(EditOperation.REMOVE_BACKGROUND);
        String fileName = editedFileName(photo.getDisplayFileName(), transparent);
        var upload = imageKitService.uploadBytes(user, bytes, fileName);
        return photoService.createDerivedPhoto(user, photo, upload, AiTransformType.AI_EDIT, fileName);
    }

    static String editedFileName(String original, boolean transparent) {
        String name = original == null || original.isBlank() ? "photo.jpg" : original;
        int dot = name.lastIndexOf('.');
        String base = dot > 0 ? name.substring(0, dot) : name;
        String extension = transparent ? ".png" : dot > 0 ? name.substring(dot) : ".jpg";
        return base + "-edited" + extension;
    }

    private Photo getActivePhoto(User user, UUID photoId) {
        Photo photo = photoRepository.findByIdAndUserId(photoId, user.getId())
                .orElseThrow(() -> new ResourceNotFoundException("Photo not found"));
        if (photo.getStatus() == PhotoStatus.TRASH) {
            throw new BadRequestException("Restore this photo before editing it");
        }
        return photo;
    }
}
